FROM openvino/ubuntu20_dev:latest

ARG DEBIAN_FRONTEND=noninteractive
ARG WHITE_CANE_DIR
ENV SERVER_ENV=dev
USER root
# update and install necessary tools
RUN pip3 install --upgrade pip

COPY requirements.txt /
WORKDIR /
RUN pip install -r requirements.txt

ENTRYPOINT ["bash"]